# Server
server.port=8080
server.servlet.context-path=/allmsisdn

# Controller base path
controller.properties.base-path=/${project.name:allmsisdn}

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# JDBC (si aplica) — TODAS con default para evitar romper arranque

# Redis properties

# RDB properties
otecel.api.rdb.host=backendpre.movistar.com.ec
otecel.api.rdb.port=32101
otecel.api.rdb.path.all.msisdn=/netcrackerrdb/allMsisdn
otecel.api.rdb.timeout=40000
otecel.api.internal.https=true
otecel.api.token=Basic YWRtaW46c1kzNU1Yei56dVg=

# Configuración general
otecel.config.blank.list=DROP,UPDATE,SELECT,DELETE,<SCRIPT>,TRUNCATE,EXEC,DELAY,SLEEP,TIMEOUT

# === Reconciliacion automatica refactor: @Value declarados explicitamente ===
otecel.api.redis.host=localhost
otecel.api.redis.path.recover=/comp/redis/v2/getDataRedis
otecel.api.redis.path.save=/comp/redis/v2/saveRedisTimeToLive
otecel.api.redis.port=8080
otecel.api.redis.timeout=20000
