# Nombre de la aplicacin Spring Boot actual
spring.application.name=ms-comp-allmsisdn
# Puerto de exposicion servicio
server.port=8080
#configuracion de logs
spring.devtools.restart.enabled=true
spring.main.banner-mode=console
spring.output.ansi.enabled=always

logging.config=/opt/ms/ms-comp-allmsisdn/log4j2.xml
controller.properties.base-path=/allmsisdn


#Para habilitar las excepciones
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

# Habilita el log de aplicacion, si se cambia el nombre de la propiedad se debe actualizar la clase LoggerConfig.java
otecel.application-log-enabled=true
# Nombre del log de aplicacion definido en la configuracion de log4j2: log4j2.xml. Por defecto si no se coloca tomar: TME_MI_APP
otecel.application-logger-name=TME_MI_APP
# Habilita el log de ejecucion, si se cambia el nombre de la propiedad se debe actualizar la clase LoggerConfig.java
otecel.execution-log-enabled=true
# Nombre del log de ejecucion definido en la configuracion de log4j2: log4j2.xml. Por defecto si no se coloca tomar: TME_MI_EXEC
otecel.execution-logger-name=TME_MI_EXEC

#Conexion postgres - Nueva configuracion para el pool de conexiones.
otecel.datasource.url:jdbc:postgresql://10.112.156.97:5436/satpush_desa?currentSchema=public 
otecel.datasource.username=otc_formaciones
otecel.datasource.password=Zp2wJX0z8VUzpkIXRgfT
otecel.datasource.configuration.maximum-pool-size=1
otecel.datasource.configuration.minimum-idle=1
otecel.datasource.configuration.driver-class-name=org.postgresql.Driver
otecel.datasource.configuration.connection-timeout=5000
otecel.datasource.configuration.validation-timeout=5000
otecel.datasource.configuration.login-timeout=5000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

#Nombres de procedimientos almacenados usados
otecel.db.getParameter=SELECT * FROM otc_get_parameter(?,?);
#Propiedades para la generacion del swagger automatico
springdoc.swagger-ui.path=/ms-comp-allmsisdn/swagger-ui.html
springdoc.api-docs.path=/ms-comp-allmsisdn/v1.0.0/api-docs
#Configuracion para compilar librerias comunes y desplegar el microservicio
otecel.devops.lib.branch=develop 
otecel.devops.lib=true
otecel.devops.deploy=true
otecel.devops.cluster.branch=ODTT-22320

#Validacion lista negra
otecel.config.blank.list=DROP,UPDATE,SELECT,DELETE,<SCRIPT>,TRUNCATE,EXEC,DELAY,SLEEP,TIMEOUT