#Ajustar al nombre del proyecto
sonar.projectKey=ms-customer-retrievebalancebuckets
sonar.projectName=ms-customer-retrievebalancebuckets
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.host.url=https://devops.movistar.com.ec:8280
sonar.login=sqa_c22dc74872f38234c52cd7b73bfa39fb3bee7433
sonar.exclusions=**/test/**,**/generated/**,**/legacy/**,**/target/**,**/lib/**
sonar.inclusions=src/main/java/**
sonar.java.binaries=target/classes