#Ajustar al nombre del proyecto
sonar.projectKey=APL-ms-comp-allmsisdn
sonar.projectName=APL-ms-comp-allmsisdn
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.host.url=https://devops.movistar.com.ec:8280
sonar.login=sqp_c53905e85a46a4227e8f3cb2c538246c5af92b87
sonar.exclusions=**/*.java
